name: Publish to Itch.io

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v3
      - name: Godot Export
        id: export
        uses: jynus/godot-export@v6.0.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.5-dev5/Godot_v4.5-dev5_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.5-dev5/Godot_v4.5-dev5_export_templates.tpz
          relative_project_path: ./src/
          archive_output: true
          cache: true
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Publish to Itch
        uses: Ayowel/butler-to-itch@v1
        with:
          butler_key: ${{secrets.ITCHIO_TOKEN}}
          itch_user: jynus
          itch_game: gmtk25
          version: ${{ github.ref_name }}
          files: "${{ steps.export.outputs.archive_directory }}/Web.zip:web" "${{ steps.export.outputs.archive_directory }}/Windows Desktop.zip:windows-64" "${{ steps.export.outputs.archive_directory }}/macOS.zip:mac" "${{ steps.export.outputs.archive_directory }}/Linux.zip:linux-64"
